const AGORA_ERROR_MSG = {
  UNEXPECTED_ERROR: '유효하지 않은 토큰이에요',
  UNEXPECTED_RESPONSE: '예상치 못한 문제가 발생했어요',
  TIMEOUT: '시간이 만료됐어요',
  INVALID_PARAMS: '예상치 못한 문제가 발생했어요',
  NOT_SUPPORTED: '예상치 못한 문제가 발생했어요',
  INVALID_OPERATION: '예상치 못한 문제가 발생했어요',
  OPERATION_ABORTED: '예상치 못한 문제가 발생했어요',
  WEB_SECURITY_RESTRICT: '예상치 못한 문제가 발생했어요',
  NETWORK_ERROR: '네트워크 오류가 발생했어요',
  NETWORK_TIMEOUT: '네트워크 오류가 발생했어요',
  NETWORK_RESPONSE_ERROR: '네트워크 오류가 발생했어요',
  API_INVOKE_TIMEOUT: '네트워크 오류가 발생했어요',
  ENUMERATE_DEVICES_FAILED: '예상치 못한 문제가 발생했어요',
  DEVICE_NOT_FOUND: '기기를 찾을 수 없어요',
  ELECTRON_IS_NULL: '예상치 못한 문제가 발생했어요',
  ELECTRON_DESKTOP_CAPTURER_GET_SOURCES_ERROR: '예상치 못한 문제가 발생했어요',
  CHROME_PLUGIN_NO_RESPONSE: '브라우저 문제가 발생했어요',
  CHROME_PLUGIN_NOT_INSTALL: '브라우저 문제가 발생했어요',
  MEDIA_OPTION_INVALID: '예상치 못한 문제가 발생했어요',
  PERMISSION_DENIED:
    '마이크 권한이 없어 접속에 실패했어요.\n마이크 권한 설정 후',
  CONSTRAINT_NOT_SATISFIED: '예상치 못한 문제가 발생했어요',
  TRACK_IS_DISABLED: '마이크 권한이 없어 실패했어요',
  SHARE_AUDIO_NOT_ALLOWED: '마이크 권한이 없어 실패했어요',
  LOW_STREAM_ENCODING_ERROR: '예상치 못한 문제가 발생했어요',
  INVALID_UINT_UID_FROM_STRING_UID: '예상치 못한 문제가 발생했어요',
  CAN_NOT_GET_PROXY_SERVER: '예상치 못한 문제가 발생했어요',
  CAN_NOT_GET_GATEWAY_SERVER: '모임이 종료 되었어요',
  VOID_GATEWAY_ADDRESS: '예상치 못한 문제가 발생했어요',
  UID_CONFLICT: '중복 접속했어요',
  INVALID_LOCAL_TRACK: '예상치 못한 문제가 발생했어요',
  INVALID_TRACK: '예상치 못한 문제가 발생했어요',
  SENDER_NOT_FOUND: '예상치 못한 문제가 발생했어요',
  CREATE_OFFER_FAILED: '예상치 못한 문제가 발생했어요',
  SET_ANSWER_FAILED: '예상치 못한 문제가 발생했어요',
  ICE_FAILED: '예상치 못한 문제가 발생했어요',
  PC_CLOSED: '예상치 못한 문제가 발생했어요',
  SENDER_REPLACE_FAILED: '예상치 못한 문제가 발생했어요',
  GATEWAY_P2P_LOST: '예상치 못한 문제가 발생했어요',
  NO_ICE_CANDIDATE: '예상치 못한 문제가 발생했어요',
  CAN_NOT_PUBLISH_MULTIPLE_VIDEO_TRACKS: '예상치 못한 문제가 발생했어요',
  EXIST_DISABLED_VIDEO_TRACK: '예상치 못한 문제가 발생했어요',
  INVALID_REMOTE_USER: '예상치 못한 문제가 발생했어요',
  REMOTE_USER_IS_NOT_PUBLISHED: '예상치 못한 문제가 발생했어요',
  CUSTOM_REPORT_SEND_FAILED: '예상치 못한 문제가 발생했어요',
  CUSTOM_REPORT_FREQUENCY_TOO_HIGH: '예상치 못한 문제가 발생했어요',
  FETCH_AUDIO_FILE_FAILED: '예상치 못한 문제가 발생했어요',
  READ_LOCAL_AUDIO_FILE_ERROR: '예상치 못한 문제가 발생했어요',
  DECODE_AUDIO_FILE_FAILED: '예상치 못한 문제가 발생했어요',
  WS_ABORT: '예상치 못한 문제가 발생했어요',
  WS_DISCONNECT: '예상치 못한 문제가 발생했어요',
  WS_ERR: '예상치 못한 문제가 발생했어요',
  LIVE_STREAMING_TASK_CONFLICT: '예상치 못한 문제가 발생했어요',
  LIVE_STREAMING_INVALID_ARGUMENT: '예상치 못한 문제가 발생했어요',
  LIVE_STREAMING_INTERNAL_SERVER_ERROR: '예상치 못한 문제가 발생했어요',
  LIVE_STREAMING_PUBLISH_STREAM_NOT_AUTHORIZED: '예상치 못한 문제가 발생했어요',
  LIVE_STREAMING_TRANSCODING_NOT_SUPPORTED: '예상치 못한 문제가 발생했어요',
  LIVE_STREAMING_CDN_ERROR: '예상치 못한 문제가 발생했어요',
  LIVE_STREAMING_INVALID_RAW_STREAM: '예상치 못한 문제가 발생했어요',
  LIVE_STREAMING_WARN_STREAM_NUM_REACH_LIMIT: '예상치 못한 문제가 발생했어요',
  LIVE_STREAMING_WARN_FAILED_LOAD_IMAGE: '예상치 못한 문제가 발생했어요',
  LIVE_STREAMING_WARN_FREQUENT_REQUEST: '예상치 못한 문제가 발생했어요',
  WEBGL_INTERNAL_ERROR: '예상치 못한 문제가 발생했어요',
  BEAUTY_PROCESSOR_INTERNAL_ERROR: '예상치 못한 문제가 발생했어요',
  CROSS_CHANNEL_WAIT_STATUS_ERROR: '예상치 못한 문제가 발생했어요',
  CROSS_CHANNEL_FAILED_JOIN_SEC: '예상치 못한 문제가 발생했어요',
  CROSS_CHANNEL_FAILED_JOIN_DEST: '예상치 못한 문제가 발생했어요',
  CROSS_CHANNEL_FAILED_PACKET_SENT_TO_DEST: '예상치 못한 문제가 발생했어요',
  CROSS_CHANNEL_SERVER_ERROR_RESPONSE: '예상치 못한 문제가 발생했어요',
  METADATA_OUT_OF_RANGE: '예상치 못한 문제가 발생했어요',
};

export default AGORA_ERROR_MSG;
