    name: Deploy to master
    
    on:
      push:
        branches:
          - master
    
    jobs:
      deploy:
        name: Build, Deploy to S3 bucket
        runs-on: [ubuntu-latest]
    
        strategy:
          matrix:
            node-version: [12.16.x]
    
        steps:
          - uses: actions/checkout@v2
    
          - name: Use Node.js ${{ matrix.node-version }}
            uses: actions/setup-node@v1
            with:
              node-version: ${{ matrix.node-version }}
          - name: Create .env
            shell: bash
            env:
              PROD_APP_ID: ${{ secrets.PROD_APP_ID }}
              PROD_API_URL: ${{ secrets.PROD_API_URL }}
              PROD_MINI_PRESET_URL: ${{ secrets.PROD_MINI_PRESET_URL }}
              GA_KEY: ${{ secrets.GA_KEY }}
              FA_KEY: ${{ secrets.FA_KEY_PROD }}
              FA_AUTH_DOMAIN: ${{ secrets.FA_AUTH_DOMAIN_PROD }}
              FA_PROJECT_ID: ${{ secrets.FA_PROJECT_ID_PROD }}
              FA_STORAGE_BUCKET: ${{ secrets.FA_STORAGE_BUCKET_PROD }}
              FA_MESSAGING_SENDER_ID: ${{ secrets.FA_MESSAGING_SENDER_ID_PROD }}
              FA_APP_ID: ${{ secrets.FA_APP_ID_PROD }}
              FA_MEASUREMENT_ID: ${{ secrets.FA_MEASUREMENT_ID_PROD }}
              INFO_NOTION_URL: ${{secrets.INFO_NOTION_URL_PROD}}
              AGORA_APP_ID: ${{secrets.AGORA_APP_ID_PROD}}
            run: |
              touch .env
              echo APP_ID="$PROD_APP_ID" >> .env
              echo API_URL="$PROD_API_URL" >> .env
              echo MINI_PRESET_URL="$PROD_MINI_PRESET_URL" >> .env
              echo GA_KEY="$GA_KEY" >> .env
              echo FA_KEY="$FA_KEY" >> .env
              echo FA_AUTH_DOMAIN="$FA_AUTH_DOMAIN" >> .env
              echo FA_PROJECT_ID="$FA_PROJECT_ID" >> .env
              echo FA_STORAGE_BUCKET="$FA_STORAGE_BUCKET" >> .env
              echo FA_MESSAGING_SENDER_ID="$FA_MESSAGING_SENDER_ID" >> .env
              echo FA_APP_ID="$FA_APP_ID" >> .env
              echo FA_MEASUREMENT_ID="$FA_MEASUREMENT_ID" >> .env
              echo INFO_NOTION_URL="$INFO_NOTION_URL" >> .env
              echo AGORA_APP_ID="$AGORA_APP_ID" >> .env
              cat .env
    
          - name: Npm install
            run: npm install
    
          - name: Build
            run: npm run build
    
          - name: Transfer to S3 for serving static
            uses: jakejarvis/s3-sync-action@master
            with:
              args: --acl public-read --follow-symlinks --delete
            env:
              AWS_S3_BUCKET: ap-madang-client-production
              AWS_ACCESS_KEY_ID: ${{ secrets. AWS_IAM_MANAGER_KEY_ID }}
              AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_IAM_MANAGER_SECRET_ACCESS_KEY }}
              AWS_REGION: ap-northeast-2
              SOURCE_DIR: 'dist'